apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ .Release.Namespace }}-quota
  namespace: {{ .Release.Namespace }}
spec:
  hard:
    requests.cpu: {{ .Values.resourceQuota.cpu }}
    requests.memory: {{ .Values.resourceQuota.memory }}
    limits.cpu: {{ .Values.resourceQuota.cpu }}
    limits.memory: {{ .Values.resourceQuota.memory }}
    pods: {{ .Values.resourceQuota.pods }}
    services: {{ .Values.resourceQuota.services }}
    persistentvolumeclaims: {{ .Values.resourceQuota.persistentvolumeclaims }}
