replicaCount: 2
image:
  repository: docker.io/kumarshubham16/live-dashboard
  tag: 1.0.0
service:
  type: ClusterIP
  port: 3000
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 200m
    memory: 350Mi
mongodb:
  image: mongo:7.0
  storageSize: 10Gi
centralDb:
  secretName: central-db-credentials
