tenant:
  name: gamma
  displayName: "Wayne Enterprises"
  planTier: free

namespace:
  labels:
    team: devops
    environment: staging

resourceQuota:
  cpu: "8"
  memory: 16Gi
  pods: "40"
  services: "20"
  persistentvolumeclaims: "10"

eventService:
  replicaCount: 1
  mysql:
    storageSize: 40Gi

liveDashboard:
  replicaCount: 1
  mongodb:
    storageSize: 40Gi

analyticsWorker:
  replicaCount: 1
  workerConcurrency: 2
  redis:
    storageSize: 40Gi

centralDb:
  host: platform-pgbouncer.platform-pgbouncer.svc.cluster.local
  port: 5432
  database: eventhub_central
