kube-prometheus-stack:
  alertmanager:
    enabled: true
    alertmanagerSpec:
      storage:
        volumeClaimTemplate:
          spec:
            accessModes: ["ReadWriteOnce"]
            storageClassName: vultr-block-storage-hdd
            resources:
              requests:
                storage: 40Gi

  grafana:
    enabled: true
    service:
      type: LoadBalancer
    persistence:
      enabled: true
      type: pvc
      storageClassName: vultr-block-storage-hdd
      size: 40Gi
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1Gi

  prometheus:
    prometheusSpec:
      retention: 15d
      storageSpec:
        volumeClaimTemplate:
          spec:
            accessModes: ["ReadWriteOnce"]
            storageClassName: vultr-block-storage-hdd
            resources:
              requests:
                storage: 40Gi
      resources:
        requests:
          cpu: 500m
          memory: 1Gi
        limits:
          cpu: 1000m
          memory: 2Gi

  prometheusOperator:
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
